[theme]
base="light" # Can be "light" or "dark" initially, will respect OS/user preference
primaryColor="#6A0DAD" # Purple
backgroundColor="#FFFFFF" # White
secondaryBackgroundColor="#F0F2F6" # Light Gray
textColor="#262730" # Dark Gray / Black
font="sans serif"

[mapbox]
# This is if you were using st.map, not relevant here but good to know.
style = "light" # or "dark", "satellite", "outdoors", etc.